### ISSUE TITLE
mavenizer fails to import non linear dependencies

### ISSUE THREAD

**Issue by adam-axon** [ivy-supplements/mavenizer#4]
I have a setup with 4 Ivy Projects. Procject A is loaded as maven project into Axon Ivy Designer 6.3. Mavenzier is able to Import Proejct B and Project C, but failes to import Project D. I think the problem is that Project C is referenced by both Project A and B with different minimal versions and mavenizer fails to load project D. In a linear setup this is not an issue. See [screenshot](https://pasteboard.co/GV7ks0f.png) for details.

**Comment by alexsuter** [comment]
mavenizer in LE should be able to handle this!
